### ISSUE TITLE
Unable to locate publishable resources

### ISSUE THREAD

**Issue by clbandoquillo** [wouterNL/laravel-drip#11]
I am using laravel v7.18.0. The following image shows the issue. Thanks!

![image](https://user-images.githubusercontent.com/22096021/86614704-fcec9300-bfe5-11ea-8dfb-fd68588edcf9.png)

**Comment by wouterNL** [comment]
I am no longer actively developing in Laravel so I am not exactly aware what the issue is. This project only accepts merge requests and is looking for new maintainers.
