### ISSUE TITLE
Undefined variable raw_json

### ISSUE THREAD

**Issue by jhull** [wouterNL/laravel-drip#3]
Getting this error when trying to make a `createOrUpdateSubscribers` call:

```Undefined variable: raw_json {"userId":463,"email":"johnny5@gmail.com","exception":"[object] (ErrorException(code: 0):  Undefined variable: raw_json at .../vendor/wouternl/laravel-drip/src/DripPhp.php:181)```

Tried all kinds of things to make it work, but I'm sure I'm missing something...

**Comment by jhull** [comment]
Now I'm getting `illegal string offset (account_id)` after `json_encode`ing my params before calling Drip. I have both Account ID and API Token set in the environment, so I'm not sure what's going on.

**Comment by wouterNL** [comment]
Have you been able to resolve this issue?
