### ISSUE TITLE
unparenthesized statements php7.4

### ISSUE THREAD

**Issue by onamfc** [wouterNL/laravel-drip#9]
any chance we can have you add a fix for php7.4's deprecated unparenthesized error? Or will you accept a pull request? Appears on lines 82, 120, 143, 177, 220, 270, & 316. solution could be - 
		( $campaigns = empty( $raw_json )
			? false
			: empty( $raw_json['campaigns'] ) )
			? array()
			: $raw_json['campaigns'];

**Comment by wouterNL** [comment]
I only accept pull requests, I am no longer actively maintaining this project.
